# Site settings
title: 诗宁
baseurl: ""
sitetitle: 诗宁博客
# timezone: TZ
description: magic5650的个人博客网站。
# author information
email: magic5650@126.com
author: Magic #yourname #magic范
place: Guangzhou #广州
domain: mobvista.com #互联网
company: Mobvista. #Mobvista.
position: Service Operations #业务运维
school: bjtu.edu.cn #北京交通大学
major: Computer Science&Technology #计算机科学与技术
resume: https://magic5650.github.io/home
profile: You will be the best. #
twitter_username: zyx19936688
weibo_username:  magic5650
github_username:  magic5650

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: magic5650   
# get one: https://disqus.com/admin/signup/
# duoshuo_shortname: clark-zhao  
# get one: http://duoshuo.com/create-site/

# blog settings
excerpt_separator: <!--more-->
permalink: /archivers/:title
gems:
 - jekyll-archives
 - jekyll-sitemap
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - rouge

repository: magic5650/magic5650.github.io
gist:
  noscript: false
# Build settings
paginate: 3
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  toc_levels: 1..3

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
